services:
  min:
    image: physino/geant4:minimal
    profiles: [ "min" ] # avoid running it by `compose up`
    command: /usr/bin/bash
    working_dir: /root/mingle
    volumes:
      - .:/root/mingle
      - ./geant4/data:/usr/share/Geant4/data
    # https://unix.stackexchange.com/a/698068/26929
    # https://stackoverflow.com/a/63291253/1801749
    environment: [ TZ=US/Central ]
    hostname: Geant4 # https://stackoverflow.com/a/63291253/1801749
    build: geant4/11.2.1
  mingle:
    image: physino/gears
    profiles: [ "mingle" ]
    command: /usr/bin/tmux new lf
    working_dir: /root/mingle
    environment: [ TZ=US/Central ]
    volumes:
      - .:/root/mingle
      - ./geant4/data:/usr/share/Geant4/data
  sshd:
    image: physino/geant4:sshd
    working_dir: /root/mingle
    ports: [ 2222:22 ]
    volumes: [ .:/root/mingle ]
    build: geant4
  g4:
    image: physino/geant4
    profiles: [ "g4" ]
    command: /usr/bin/bash
    working_dir: /root/mingle
    volumes:
      - .:/root/mingle
    build: geant4
